plugins:
  mumble_enabled:
    default: true
    client: true
  mumble_interval:
    default: 60000
    client: true
  mumble_cvp:
    default: ''
  mumble_xml:
    default: false
  mumble_show_empty_channels:
    default: false
    client: true
